<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-U3TR6TQ" ignored="0" name="Default test" tests="14" failures="5" timestamp="19 May 2023 04:17:21 GMT" time="3.565" errors="0">
  <testcase name="runScenario" time="0.169" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.008" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.031" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [12] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [12] but found [10]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at stepDefinations.Loginsteps.user_enter_valid_username_as_and_password_as(Loginsteps.java:49)
at ✽.user enter valid username as Name1 and password as password1(file:///C:/SeleniumWorkSpaces/May2023_APITestingWithRESTFulForSynechron/Cucumber_APITesting/src/test/java/features/LoginParam.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="0.006" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [12] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [12] but found [10]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at stepDefinations.Loginsteps.user_enter_valid_username_as_and_password_as(Loginsteps.java:49)
at ✽.user enter valid username as Name2 and password as password2(file:///C:/SeleniumWorkSpaces/May2023_APITestingWithRESTFulForSynechron/Cucumber_APITesting/src/test/java/features/LoginParam.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="0.005" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [12] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [12] but found [10]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at stepDefinations.Loginsteps.user_enter_valid_username_as_and_password_as(Loginsteps.java:49)
at ✽.user enter valid username as Name3 and password as password3(file:///C:/SeleniumWorkSpaces/May2023_APITestingWithRESTFulForSynechron/Cucumber_APITesting/src/test/java/features/LoginParam.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="0.004" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [12] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [12] but found [10]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at stepDefinations.Loginsteps.user_enter_valid_username_as_and_password_as(Loginsteps.java:49)
at ✽.user enter valid username as Name4 and password as password4(file:///C:/SeleniumWorkSpaces/May2023_APITestingWithRESTFulForSynechron/Cucumber_APITesting/src/test/java/features/LoginParam.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="0.005" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [12] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [12] but found [10]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at stepDefinations.Loginsteps.user_enter_valid_username_as_and_password_as(Loginsteps.java:49)
at ✽.user enter valid username as Name5 and password as password5(file:///C:/SeleniumWorkSpaces/May2023_APITestingWithRESTFulForSynechron/Cucumber_APITesting/src/test/java/features/LoginParam.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="0.493" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.035" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.024" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.025" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.021" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.033" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.015" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
</testsuite> <!-- Default test -->
